#include <stdio.h>
#include <string.h>
#include <time.h>

#include "sgAlign.h"
#include "sgAlignSSE.h"

char anchor[] = "CTGTACTCCTGTGCTTAAGATCAAAATTATTTCTCAACGCCAAACATACGTTCTTAAACC",
     ref[] =
  "GTGAGACTACGAGGGATAGTATCGTCACTAGTATGGCGCCCTGAATGTGGAAAGACGCCA"
  "CGGCGCTCATGATGTGACAATCTCATGACTAGTTCCGTCAACGGCAGCGCTTCAGTCACA"
  "GGACGCAAGGAAGCCGTGATCAAATAGCCTTACCCACGCATGGGTCCCCTAGGGCAAATA"
  "ACAATACAAGATCCGGTGTATAGATTGTGGCACGACTTGGCAGGAATCACGGATTACATG"
  "ATATAGTTATCAACTAGTCCGACATGTCAAATCTGCAGCGGACATTACGAAGCGGGCCTT"
  "CATATAATGAGAGCCATCGCCTATGTAGGCCGCAGACAAATCAGTACGTTGGAGCTTCGA"
  "GTCCCATATGGCCCAGCCCGGCTCCGGGTATGAGAACATCTTGCATTAGATCGGTTGACT"
  "TGTATCCAATGTTTTCTGCAATCATACAAGTGGTGCCTCGTAAGGGGCCAACGATCGATA"
  "TATGTTGCTTTGTGCATTAACGTCTGTACCACTTTATCATCACGTGACACAAGATAGGAG"
  "CAAAGAATGCAAATTCCTTACTGGGGCAAATCGACTAGCACCGCGCGATCGTTACACCTG"
  "GCATAAAACCCCGATGTGTGTGGGCTGTGGGGCTGGACCTCTGAAGACCTCTGTGCTCAA"
  "CTTCCTATTAGACGAGCATTCATTGCGATATCGATGACCCAGTAGAAATTTCCTGCTTCA"
  "TTTCTTGTGGACGTAGTGCTAGGCGTAGCTGCGAGAATTACTTCACACAATGCCTAATAA"
  "CAGAATAATGAACGTATCTTAAGAAAATGGCATTGCGAGTAGCGGCAGACGCCTCATCTG"
  "GTAGTTTAACCCATTGCCGACACCCGCTTACGAAGTCCCCTGTAATTGGGGTTACTCACA"
  "TCGGTCCAGGTTATCGTTCACTACCAAAGGTATTCGCTCGTAACTTGCTAGCCACAGTAC"
  "TACTGAGGGGTTTGTGACGCCGGTTCCTTATTGGATGCTA";


clock_t benchmark(alignment (*f)(char *, char *, unsigned char)) {
  clock_t t = clock();
  int i;

  for (i = 0; i < 1000; i++) {
    f(ref, anchor, 1);
  }

  return clock() - t;
}


int main(void) {
  char *_anchor = (char *)malloc(strlen(anchor) * sizeof(char));
  clock_t vanilla,
          sse;
  int i,
      j;

  strcpy(_anchor, anchor);
  printf("ref\tanchor\tvanilla\tsse\tdiff\tfraq\n");
  for (i = 1000; i > 60; i -= 10) {
    strcpy(anchor, _anchor);
    ref[i] = '\0';

    for (j = 60; j; j -= 5) {
      anchor[j] = '\0';

      vanilla = benchmark(align);
      sse = benchmark(alignSSE);

      printf(
        "%i\t%i\t%i\t%i\t%i\t%f\n",
        i, j, vanilla, sse, vanilla - sse, (float)vanilla / sse);
    }
  }

  return 0;
}
